package gui;

import bd.Conector;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Master01
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    private Conector conector = new Conector();
    
    public LoginForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private boolean register_form_active = false;
     private RegisterForm rf;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaError = new javax.swing.JDialog();
        Base_Dialogo_Fondo = new javax.swing.JPanel();
        Base_Dialogo = new javax.swing.JPanel();
        texto = new javax.swing.JLabel();
        Base = new javax.swing.JPanel();
        Base_Derecha_Panel_Login = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        usernameIcon = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        Base_Izquierda_Panel_Login = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        compareFaster = new javax.swing.JLabel();
        saveFaster = new javax.swing.JLabel();

        Base_Dialogo_Fondo.setBackground(new java.awt.Color(0, 0, 0));
        Base_Dialogo_Fondo.setToolTipText("Base Decorativa, separa de Base activa en el panel de login");

        Base_Dialogo.setBackground(new java.awt.Color(255, 133, 50));
        Base_Dialogo.setToolTipText("Base Login Con los items de acción");

        texto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        texto.setText("             Datos Erroneos!, comprueba los datos o regístrate!");
        texto.setToolTipText("Texto alerta");

        javax.swing.GroupLayout Base_DialogoLayout = new javax.swing.GroupLayout(Base_Dialogo);
        Base_Dialogo.setLayout(Base_DialogoLayout);
        Base_DialogoLayout.setHorizontalGroup(
            Base_DialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Base_DialogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                .addContainerGap())
        );
        Base_DialogoLayout.setVerticalGroup(
            Base_DialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Base_DialogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Base_Dialogo_FondoLayout = new javax.swing.GroupLayout(Base_Dialogo_Fondo);
        Base_Dialogo_Fondo.setLayout(Base_Dialogo_FondoLayout);
        Base_Dialogo_FondoLayout.setHorizontalGroup(
            Base_Dialogo_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
            .addGroup(Base_Dialogo_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Base_Dialogo_FondoLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(Base_Dialogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        Base_Dialogo_FondoLayout.setVerticalGroup(
            Base_Dialogo_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
            .addGroup(Base_Dialogo_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Base_Dialogo_FondoLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(Base_Dialogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(23, 23, 23)))
        );

        javax.swing.GroupLayout ventanaErrorLayout = new javax.swing.GroupLayout(ventanaError.getContentPane());
        ventanaError.getContentPane().setLayout(ventanaErrorLayout);
        ventanaErrorLayout.setHorizontalGroup(
            ventanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaErrorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Base_Dialogo_Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ventanaErrorLayout.setVerticalGroup(
            ventanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Base_Dialogo_Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Base.setToolTipText("Base absoluta de el formulario de login");

        Base_Derecha_Panel_Login.setBackground(new java.awt.Color(255, 133, 50));
        Base_Derecha_Panel_Login.setToolTipText("Base Login Con los items de acción");

        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-login-64.png"))); // NOI18N
        LoginButton.setToolTipText("Boton para loguearse");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        RegisterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-register-64.png"))); // NOI18N
        RegisterButton.setToolTipText("Boton para registrarse");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        usernameField.setBackground(new java.awt.Color(0, 0, 0));
        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.setText("Usuario");
        usernameField.setToolTipText("Username Field");
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(0, 0, 0));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setToolTipText("Password field");

        usernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-username-50.png"))); // NOI18N
        usernameIcon.setToolTipText("Username Icon");

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-lock-50.png"))); // NOI18N
        passwordIcon.setToolTipText("Password Icon");

        javax.swing.GroupLayout Base_Derecha_Panel_LoginLayout = new javax.swing.GroupLayout(Base_Derecha_Panel_Login);
        Base_Derecha_Panel_Login.setLayout(Base_Derecha_Panel_LoginLayout);
        Base_Derecha_Panel_LoginLayout.setHorizontalGroup(
            Base_Derecha_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Base_Derecha_Panel_LoginLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterButton)
                .addGap(59, 59, 59))
            .addGroup(Base_Derecha_Panel_LoginLayout.createSequentialGroup()
                .addGroup(Base_Derecha_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Base_Derecha_Panel_LoginLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(usernameIcon))
                    .addGroup(Base_Derecha_Panel_LoginLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(passwordIcon)))
                .addGap(131, 131, 131)
                .addGroup(Base_Derecha_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(passwordField))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        Base_Derecha_Panel_LoginLayout.setVerticalGroup(
            Base_Derecha_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Base_Derecha_Panel_LoginLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(Base_Derecha_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameIcon))
                .addGap(92, 92, 92)
                .addGroup(Base_Derecha_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField))
                .addGap(224, 224, 224)
                .addGroup(Base_Derecha_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(RegisterButton))
                .addContainerGap(324, Short.MAX_VALUE))
        );

        Base_Izquierda_Panel_Login.setBackground(new java.awt.Color(0, 0, 0));
        Base_Izquierda_Panel_Login.setToolTipText("Base Decorativa, separa de Base activa en el panel de login");

        Header.setBackground(new java.awt.Color(0, 142, 122));
        Header.setToolTipText("Pannel que contiene logo");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bsmart_logo.png"))); // NOI18N
        Logo.setToolTipText("Etiqueta con logo");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        compareFaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CompareFaster.png"))); // NOI18N
        compareFaster.setToolTipText("icon for Compare Faster");

        saveFaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SaveFaster.png"))); // NOI18N
        saveFaster.setToolTipText("Icon for Save faster");

        javax.swing.GroupLayout Base_Izquierda_Panel_LoginLayout = new javax.swing.GroupLayout(Base_Izquierda_Panel_Login);
        Base_Izquierda_Panel_Login.setLayout(Base_Izquierda_Panel_LoginLayout);
        Base_Izquierda_Panel_LoginLayout.setHorizontalGroup(
            Base_Izquierda_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Base_Izquierda_Panel_LoginLayout.createSequentialGroup()
                .addGroup(Base_Izquierda_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Base_Izquierda_Panel_LoginLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Base_Izquierda_Panel_LoginLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(Base_Izquierda_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveFaster)
                            .addComponent(compareFaster))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        Base_Izquierda_Panel_LoginLayout.setVerticalGroup(
            Base_Izquierda_Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Base_Izquierda_Panel_LoginLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(compareFaster)
                .addGap(120, 120, 120)
                .addComponent(saveFaster)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaseLayout.createSequentialGroup()
                .addComponent(Base_Izquierda_Panel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 556, Short.MAX_VALUE))
            .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaseLayout.createSequentialGroup()
                    .addContainerGap(881, Short.MAX_VALUE)
                    .addComponent(Base_Derecha_Panel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base_Izquierda_Panel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BaseLayout.createSequentialGroup()
                    .addComponent(Base_Derecha_Panel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        
        /**
         * Bloque de código el cual garantiza que no se 
         * puedan generar ventanas de registro infinitas
         */
        if (this.register_form_active == false){
            this.rf = new RegisterForm();
            rf.setVisible(true);
            this.register_form_active = true;
        }else{
            this.rf.dispose();
            this.register_form_active = false;
        }

    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        boolean valido = this.conector.comprobar_usuario(this.usernameField.getText(),this.passwordField.getText());
        
        if (valido == false){
            this.ventanaError.setVisible(true);
            this.ventanaError.setSize(900, 300);
            this.ventanaError.setModal(true);
        }
        else{
            Hub hub = new Hub();
            hub.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Base_Derecha_Panel_Login;
    private javax.swing.JPanel Base_Dialogo;
    private javax.swing.JPanel Base_Dialogo_Fondo;
    private javax.swing.JPanel Base_Izquierda_Panel_Login;
    private javax.swing.JPanel Header;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel compareFaster;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel saveFaster;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameIcon;
    private javax.swing.JDialog ventanaError;
    // End of variables declaration//GEN-END:variables
}
