package gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Master01
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePaneBlack = new javax.swing.JPanel();
        basePaneOrange = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        passwordField1 = new javax.swing.JPasswordField();
        passwordField2 = new javax.swing.JPasswordField();
        usernameField1 = new javax.swing.JTextField();
        usernameIcon1 = new javax.swing.JLabel();
        passwordIcon1 = new javax.swing.JLabel();
        usernameField2 = new javax.swing.JTextField();
        usernameIcon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePaneBlack.setBackground(new java.awt.Color(0, 0, 0));
        basePaneBlack.setToolTipText("base panel for register form");

        basePaneOrange.setBackground(new java.awt.Color(255, 133, 50));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-double-left-50.png"))); // NOI18N
        backButton.setToolTipText("Back button");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-save-50.png"))); // NOI18N
        registerButton.setToolTipText("Register Buton");

        passwordField1.setBackground(new java.awt.Color(0, 0, 0));
        passwordField1.setForeground(new java.awt.Color(255, 255, 255));
        passwordField1.setToolTipText("Password field 2");

        passwordField2.setBackground(new java.awt.Color(0, 0, 0));
        passwordField2.setForeground(new java.awt.Color(255, 255, 255));
        passwordField2.setToolTipText("Password field 1");

        usernameField1.setBackground(new java.awt.Color(0, 0, 0));
        usernameField1.setForeground(new java.awt.Color(255, 255, 255));
        usernameField1.setText("Nuevo Usuario");
        usernameField1.setToolTipText("Username Field");
        usernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField1ActionPerformed(evt);
            }
        });

        usernameIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-username-50.png"))); // NOI18N
        usernameIcon1.setToolTipText("Username Icon");

        passwordIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-lock-50.png"))); // NOI18N
        passwordIcon1.setToolTipText("Password Icon");

        usernameField2.setBackground(new java.awt.Color(0, 0, 0));
        usernameField2.setForeground(new java.awt.Color(255, 255, 255));
        usernameField2.setText("Nuevo Correo");
        usernameField2.setToolTipText("Email Field");
        usernameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField2ActionPerformed(evt);
            }
        });

        usernameIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-circled-envelope-50.png"))); // NOI18N
        usernameIcon2.setToolTipText("EmaiIcon");

        javax.swing.GroupLayout basePaneOrangeLayout = new javax.swing.GroupLayout(basePaneOrange);
        basePaneOrange.setLayout(basePaneOrangeLayout);
        basePaneOrangeLayout.setHorizontalGroup(
            basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePaneOrangeLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePaneOrangeLayout.createSequentialGroup()
                        .addGroup(basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, basePaneOrangeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(basePaneOrangeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameIcon2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(usernameIcon1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordIcon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(passwordField2)
                                    .addComponent(usernameField1)
                                    .addComponent(usernameField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                        .addGap(80, 80, 80))
                    .addGroup(basePaneOrangeLayout.createSequentialGroup()
                        .addComponent(backButton)
                        .addContainerGap(383, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePaneOrangeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(31, 31, 31))
        );
        basePaneOrangeLayout.setVerticalGroup(
            basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePaneOrangeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(basePaneOrangeLayout.createSequentialGroup()
                        .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(basePaneOrangeLayout.createSequentialGroup()
                        .addComponent(usernameIcon1)
                        .addGap(18, 18, 18)))
                .addGroup(basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameIcon2))
                .addGap(31, 31, 31)
                .addGroup(basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordIcon1)
                    .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(basePaneOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton)
                    .addComponent(backButton))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout basePaneBlackLayout = new javax.swing.GroupLayout(basePaneBlack);
        basePaneBlack.setLayout(basePaneBlackLayout);
        basePaneBlackLayout.setHorizontalGroup(
            basePaneBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePaneBlackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basePaneOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basePaneBlackLayout.setVerticalGroup(
            basePaneBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePaneBlackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basePaneOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePaneBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePaneBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField1ActionPerformed

    private void usernameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField2ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel basePaneBlack;
    private javax.swing.JPanel basePaneOrange;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JLabel passwordIcon1;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameField1;
    private javax.swing.JTextField usernameField2;
    private javax.swing.JLabel usernameIcon1;
    private javax.swing.JLabel usernameIcon2;
    // End of variables declaration//GEN-END:variables
}
